// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpdepacuuqbfyzfzpumm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwZGVwYWN1dXFiZnl6ZnpwdW1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDAwMDksImV4cCI6MjA3NDM3NjAwOX0.hrQApNhw5JUGHfGApIpTY918KXrTNmcXhRH3rXmTnS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});